<a href="https://colab.research.google.com/github/Valeria19k/Ball/blob/main/pr12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip3 install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 129 kB/s 


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier

df = load_wine()
df

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [6]:
predicts = df.data
target = df.target
print(predicts,'\n\n',target)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [7]:
print(predicts.shape)

(178, 13)


In [11]:
A_train, A_test, y_train, y_test = train_test_split(predicts, target, train_size = 0.8)
print(A_train.shape,'\n\n', A_test.shape)

(142, 13) 

 (36, 13)


In [12]:
random_forest = RandomForestClassifier(max_depth = 15, min_samples_split = 10).fit(A_train, y_train)
y_preds_d = random_forest.predict(A_train)
y_pred = random_forest.predict(A_test)
print('F1 мера для тренировочных данных', f1_score(y_preds_d, y_train, average = 'macro'))
print('F1 мера для тестовых данных', f1_score(y_pred, y_test, average = 'macro'))

F1 мера для тренировочных данных 1.0
F1 мера для тестовых данных 0.8952472293265131


In [14]:
random_forest = RandomForestClassifier()
params_grid = {
    "max_depth": [12, 18],
    "min_samples_leaf": [3, 10],
    "min_samples_split": [6, 12]
}
grid_search_random_forest = GridSearchCV(estimator=random_forest,param_grid=params_grid,scoring="f1_macro",cv=4)
grid_search_random_forest.fit(A_train, y_train)
GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1), param_grid={'max_depth': [12, 18], 'min_samples_leaf': [3, 10], 'min_samples_split': [6, 12]}, scoring = 'f1_macro')
best_model = grid_search_random_forest.best_estimator_
y_preds_d = best_model.predict(A_train)
y_pred = best_model.predict(A_test)
print('F1 мера для тренировочных данных', f1_score(y_preds_d, y_train, average = 'macro'))
print('F1 мера для тестовых данных', f1_score(y_pred, y_test, average = 'macro')) 

F1 мера для тренировочных данных 1.0
F1 мера для тестовых данных 0.9203563145688382


In [15]:
import catboost as cb

model_catboost_clf = cb.CatBoostClassifier(iterations=3000, task_type="GPU", devices='0')
model_catboost_clf.fit(A_train, y_train)

Learning rate set to 0.017455
0:	learn: 1.0771361	total: 8.67ms	remaining: 26s
1:	learn: 1.0558695	total: 16.4ms	remaining: 24.6s
2:	learn: 1.0356195	total: 24ms	remaining: 24s
3:	learn: 1.0187629	total: 42.7ms	remaining: 32s
4:	learn: 0.9981826	total: 50.2ms	remaining: 30.1s
5:	learn: 0.9792616	total: 57.8ms	remaining: 28.8s
6:	learn: 0.9610220	total: 65.5ms	remaining: 28s
7:	learn: 0.9419949	total: 73ms	remaining: 27.3s
8:	learn: 0.9250949	total: 80.6ms	remaining: 26.8s
9:	learn: 0.9086706	total: 88.3ms	remaining: 26.4s
10:	learn: 0.8926314	total: 95.8ms	remaining: 26s
11:	learn: 0.8771680	total: 103ms	remaining: 25.8s
12:	learn: 0.8617285	total: 111ms	remaining: 25.5s
13:	learn: 0.8476893	total: 119ms	remaining: 25.4s
14:	learn: 0.8343108	total: 127ms	remaining: 25.2s
15:	learn: 0.8199740	total: 134ms	remaining: 25s
16:	learn: 0.8062751	total: 141ms	remaining: 24.8s
17:	learn: 0.7923190	total: 154ms	remaining: 25.5s
18:	learn: 0.7784972	total: 162ms	remaining: 25.4s
19:	learn: 0.765

In [16]:
y_preds_t = model_catboost_clf.predict(A_train, task_type="CPU")
y_preds = model_catboost_clf.predict(A_test, task_type="CPU")
print('F1 мера для тренировочных данных', f1_score(y_preds_t, y_train, average = 'macro'))
print('F1 мера для тестовых данных', f1_score(y_preds, y_test, average = 'macro')) 

F1 мера для тренировочных данных 1.0
F1 мера для тестовых данных 0.9203563145688382
